### ISSUE TITLE
Not working on 1.5.3

### ISSUE THREAD

**Issue by donizettilorenzo** [Ishmaeel/FireModeCheck#10]
Not working on 1.5.3 (it's always in basic mode)

**Comment by Ishmaeel** [comment]
Confirmed. Thank you for adding the detail about basic mode.

**Comment by Ishmaeel** [comment]
Fixed.

**Comment by donizettilorenzo** [comment]
Thanks man!

**Comment by donizettilorenzo** [comment]
One request (for possible future evolutions): add a choice related to press vs long press of the same key (press->change firemode like in the "basic" preset vs long press->check firemode)
